# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: afe9bc0a73f2c341ba1b1764b6d4a401eee10f0f7a9a7233926b067bf44661085c389ebc40757f54e5c688ce4c897a999fdd0192b72889fb9a28a6f5aa383a31

test:
  secret_key_base: ed7700d240c5c16667226470c9a793bb7750df43fedfb4a82f60e18ce96cecacb347143827953d6be1fec79617b56f1d2878c484875c30f579f95eda86a45e06

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
